# Default values for UB(Union Board).
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  ingress:
    hosts:
    - host: "host-path" # Host address
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: web-devbox-kr-cert
      hosts:
      - "host-path" # Host address

web:
  imageConfigMaps:
    djangoSettingsModule: _config.settings.prod
