apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
data:
  DEFAULT.CONF: |
    upstream backend {
        server web:9000;
    }
    # 클라이언트 요청 크기 설정 (예: 50MB)
    client_max_body_size 50M;
    server {
        listen {{ .Values.service.port | default "80" }} default_server;
        listen [::]:{{ .Values.service.port | default "80" }} default_server;
        charset         utf-8;

        server_name $host localhost;

        root /var/www/html;
        index index.php index.html;

        # Support Yii2 pretty URL routing
        location / {
            try_files $uri $uri/ =404;
            if (!-e $request_filename){
                rewrite ^/(.*) /index.php?r=$1 last;
            }
            proxy_hide_header Access-Control-Allow-Origin;
            add_header 'Access-Control-Allow-Origin' '*';
        }

        location ~* \.php$ {
            fastcgi_pass backend;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        }

        # Prevent additional headers like TRACE, DELETE, PUSH
        if ($request_method !~ ^(GET|HEAD|POST)$ )
        {
            return 405;
        }
    }