apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-config
data:
  BASE_URL: "{{ .Values.global.baseUrl }}"
  ENCRYPTION_KEY: "{{ .Values.global.encryptionKey }}"
  DATABASE_HOST: "mariadb"
  DATABASE_NAME: "{{ .Release.Name }}"
  DATABASE_USER: "{{ .Release.Name }}"