apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-config
data:
  BASE_URL: "{{ .Values.global.baseUrl }}"
  ENCRYPTION_KEY: "{{ randAlphaNum 5 }}"
  DATABASE_HOST: "{{ default "mariadb" .Values.global.dbHost }}"
  DATABASE_NAME: "{{ .Release.Name }}"
  DATABASE_USER: "{{ .Release.Name }}"