apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ default b64enc "secret" tpl .Values.global.dbPassword . | b64enc }}
