apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ tpl (default "secret" .Values.global.dbPassword) . | b64enc }}
  EMAIL_PASS: "{{ tpl .Values.global.emailPassword . | b64enc }}"
