apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "web.fullname" . }}-django-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: {{ include "web.fullname" . }}-app-{{ .Values.global.appMode }}
  capacity:
  {{- if eq .Values.global.appMode "prod" }}
    storage: {{ .Values.volumes.djangoPvStorageProd }}
  {{- else if eq .Values.global.appMode "dev" }}
    storage: {{ .Values.volumes.djangoPvStorageDev }}
  {{- end }}
  accessModes:
    {{- range .Values.volumes.djangoAccessModes }}
    - {{ . }}
    {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    {{- if eq .Values.global.appMode "prod" }}
    path: {{ .Values.global.nfsPath }}/prod/app/django
    {{- else if eq .Values.global.appMode "dev" }}
    path: {{ .Values.global.nfsPath }}/dev/app/django
    {{- end }}
    server: {{ .Values.global.nfsServerHost }}
