# Default values for ub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nfsServerHost: "nfs-server-host"  # NFS_HOST = nfs server host (ip)
  nfsPath: "" # NFS_PATH = nfs volume path
  baseUrl: "" # BASE_URL
  dbHost: ""  # DATABASE_HOST (default: mariadb)
  dbName: ""  # DATABASE_NAME (default: ReleaseName)
  dbUser: "" # DATABASE_USER (default: ReleaseName)
  dbPassword: "" # DATABASE_PASS (default: secret)
  emailHost: "smtp-server.com" # your-smtp-server.com
  emailUser: "email@example.com" # 'your-email@example.com
  emailPassword: "{{ randAlphaNum 5 }}" # your-email-password

nginx:
  service:
    type: LoadBalancer
    port: 8888
  
  ingress:
    enabled: true
    
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "100M"
      cert-manager.io/cluster-issuer: letsencrypt-ub
    hosts:
      - host: "host-path" # DOMAIN_NAME = Host address
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: ub-certificate-tls
        hosts:
          - "host-path" # DOMAIN_NAME = Host address
