# Default values for ub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nfsServerHost: "nfs-server-host"
  nfsPath: "" # nfs volume path
  baseUrl: "http://localhost:8080/"
  dbHost: ""
  dbName: ""
  dbUser: ""
  dbPassword: ""

nameOverride: ""
fullnameOverride: ""

mariadb:
  volumes:
    nfsServerHost: ""

nginx:
  service:
    type: LoadBalancer
    port: 8888
  
  ingress:
    enabled: true
    
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
#      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "100M"
      cert-manager.io/cluster-issuer: letsencrypt-ub
    hosts:
      - host: "host-path" # Host address
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: ub-certificate-tls
        hosts:
          - "host-path" # Host address

