apiVersion: v1
data:
  MYSQL_DATABASE: "{{ .Values.global.dbName | default .Release.Name }}"
  MYSQL_USER: "{{ .Values.global.dbUser | default .Release.Name }}"
  TZ: "{{ .Values.timeZone }}"
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-config
