apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.fullname" . }}-data-pvc
spec:
  storageClassName: mysql-data
  accessModes:
  {{- range .Values.volumes.dataAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.dataPvcStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.fullname" . }}-sql-pvc
spec:
  storageClassName: {{ include "ub.fullname" . }}-init-sql
  accessModes:
  {{- range .Values.volumes.sqlAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.sqlPvcStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.fullname" . }}-backup-pvc
spec:
  storageClassName: {{ include "ub.fullname" . }}-dump-backup
  accessModes:
  {{- range .Values.volumes.backupAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.backupPvcStorage }}
