apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ default "secret" | b64enc tpl .Values.global.dbPassword . | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ default "secret" | b64enc tpl .Values.global.dbPassword . | b64enc }}
