apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ tpl .Values.global.dbPassword . | b64enc }}
  EMAIL_HOST_PASSWORD: {{ tpl .Values.global.emailHostPassword . | b64enc }}
{{/*  {{- with  .Values.imageSecrets }}*/}}
{{/*  AWS_ACCESS_KEY_ID: {{ .awsAccessKeyId }}*/}}
{{/*  AWS_SECRET_ACCESS_KEY: {{ .awsSecretAccessKey }}*/}}
{{/*  {{- end }}*/}}
