apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx.fullname" . }}-static-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: {{ include "nginx.fullname" . }}-static-{{ .Values.global.appMode }}
  capacity:
  {{- if eq .Values.global.appMode "prod" }}
    storage: {{ .Values.volumes.staticStorageProd }}
  {{- else if eq .Values.global.appMode "dev" }}
    storage: {{ .Values.volumes.staticStorageDev }}
  {{- end }}
  accessModes:
  {{- range .Values.volumes.RWMAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
  {{- if eq .Values.global.appMode "prod" }}
    path: {{ .Values.global.nfsPath }}/prod/app/django/static
  {{- else if eq .Values.global.appMode "dev" }}
    path: {{ .Values.global.nfsPath }}/dev/app/django/static
  {{- end }}
    server: {{ .Values.global.nfsServerHost }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx.fullname" . }}-media-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: {{ include "nginx.fullname" . }}-media-{{ .Values.global.appMode }}
  capacity:
  {{- if eq .Values.global.appMode "prod" }}
    storage: {{ .Values.volumes.mediaStorageProd }}
  {{- else if eq .Values.global.appMode "dev" }}
    storage: {{ .Values.volumes.mediaStorageDev }}
  {{- end }}
  accessModes:
  {{- range .Values.volumes.RWMAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
  {{- if eq .Values.global.appMode "prod" }}
    path: {{ .Values.global.nfsPath }}/prod/app/django/media
  {{- else if eq .Values.global.appMode "dev" }}
    path: {{ .Values.global.nfsPath }}/dev/app/django/media
  {{- end }}
    server: {{ .Values.global.nfsServerHost }}
