apiVersion: v1
data:
  MYSQL_DATABASE: "{{ .Release.Name }}"
  MYSQL_USER: "{{ .Release.Name }}"
  TZ: "{{ .Values.timeZone }}"
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-config
