apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mariadb.fullname" . }}-data-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: mysql-data-{{ .Values.global.appMode }}
  capacity:
    storage: {{ .Values.volumes.dataPvStorageProd }}
  accessModes:
  {{- range .Values.volumes.dataAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.global.cicdPath }}/ub/volume/mysql
    server: {{ .Values.global.cicdServerHost }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mariadb.fullname" . }}-sql-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: init-sql-{{ .Values.global.appMode }}
  capacity:
    storage: {{ .Values.volumes.sqlPvStorage }}
  accessModes:
  {{- range .Values.volumes.sqlAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.global.nfsPath }}/ub/volume/sql
    server: {{ .Values.global.nfsServerHost }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mariadb.fullname" . }}-backup-{{ .Values.global.appMode }}-nfs-pv
spec:
  storageClassName: dump-backup-{{ .Values.global.appMode }}
  capacity:
    storage: {{ .Values.volumes.backupPvStorageProd }}
  accessModes:
  {{- range .Values.volumes.backupAccessModes }}
    - {{ . }}
  {{- end }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.global.nfsPath }}/ub/volume/backups
    server: {{ .Values.global.nfsServerHost }}
