apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ub # name of clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com # Let's Encrypt account email
    privateKeySecretRef:
      name: letsencrypt-ub  # name of clusterissuer
    solvers:
    - http01:
        ingress:
          class:  nginx  # Ingress class in use
